# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git' 
platform :ios, '9.0'

target 'WalkProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalkProject

  target 'WalkProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WalkProjectUITests' do
    # Pods for testing
  end

pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'Masonry', '~>1.0.2'
pod 'QMUIKit'
pod 'IQKeyboardManager', '~>5.0.8'
pod 'YTKNetwork'
# pod 'ReactiveObjC', '~> 3.0.0'
pod 'JSONModel', '~> 1.7.0'
pod 'MJRefresh','~>3.1.15.1'
# pod 'RxCocoa','~>4.4.0'
# pod 'JPush', '~> 3.1.0'
# pod 'TZImagePickerController', '~>3.2.7'

end
